name: ngWanling
analytics: {}
github: true
description: Wan Ling's Portfolio
author:
  name: Wan Ling
  email: wanling96@gmail.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/57f4f453-d8e8-4253-801b-b37247da07c7.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/57f4f453-d8e8-4253-801b-b37247da07c7.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
layout_spectrum: 0.3310326803475618
color:
  lightness: 0.9684654723313789
  brandColors:
    - '#962D3E'
    - '#343642'
    - '#979C9C'
    - '#F2EBC7'
    - '#348899'
  saturation: 0.7434810895341172
  brandStrength: 0.9408949401557667
  rhythmicContrast: 0.4484854006321368
content_rating:
  adult: false
typography_spectrum: 0.4455348199699074
opengraph: {}
title: Ng Wan Ling Teaching Portfolio
